# These are supported funding model platforms

# github: [yourusername]  # Replace with your GitHub Sponsors username
# patreon: yourusername   # Replace with your Patreon username
# open_collective: projectname  # Replace with your Open Collective name
# ko_fi: yourusername     # Replace with your Ko-fi username
# buy_me_a_coffee: yourusername  # Replace with your Buy Me a Coffee username

# Uncomment and add your preferred funding platform(s) above
# This allows people to sponsor your project via GitHub's "Sponsor" button

